export const root: string;
export const leading: string;
export const trailing: string;
export const current: string;
export const name: string;
export const time: string;
export const icon: string;
export const description: string;
export const info: string;
